### ISSUE TITLE
Building errors when using SalviaRenderer

### ISSUE THREAD

**Issue by WilliamWangPeng** [wuye9036/SalviaRenderer#27]
HI dear author,
It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/127169337-5faaf1ea-a1e0-4f57-bebc-c30a8128cd96.png)

thank you  
best regards to you  
William

**Comment by wuye9036** [comment]
What is your python version? It is the type hint feature supported from python 3.5. 

https://docs.python.org/3/library/typing.html

**Comment by wuye9036** [comment]
Python build script was deprecated and removed from project.
